/*   
    OPERADORES DE COMPARACAO
 >   MAIOR QUE
 >=  MAIOR OU IGUAL A
 <   MENOR QUE
 <=  MENOR OU IGUAL A
 ==  IGUALDADE (VALOR)
 === IGUALDADE ESTRITA (VALOR E TIPO)
 !=  DIFERENTE (VALOR)
 !== DIFERENTE ESTRITO (VALOR E TIPO)

 ESSAS COMPARACOES RETORNAM BOOLEANOS (VERDADEIRO OU FALSO)

*/

const num = 10;
const num2 = '10';
console.log(num == num2);

//Maneira correta
console.log(num ===num2);